export const query = (content) => {
  return {
    model: "gpt-3.5-turbo",
    messages: [
      {
        role: "user",
        content: `Please generate an overview of this survey data ${content}, in the form of a JSON with the following structure: {question1: "overview of question 1", question2: "overview of question 2", ...,"What the positive responses of the survey says..":"An analyzed overview of the positive responses of all questions implying where they are good at and ending with a highlight of the most postive response of the survey","What the negative responses of the survey says..":"An analyzed overview of the negative responses of all questions implying where they are bad at and the areas of improvement and ending with a highlight of the most negative response of the survey", "Overall Overview of the survey": "an analyzed overview of all responses of all questions and end it with whether the survey had positive feedback or negative one"}.For the overview of the reponses of the individual questions, I don't want the overview like statistcs , the overview should be like an summary or inference or what the responses try to mean like that.  Ensure that the overview is generated by analyzing all the responses and providing insights. Remove any unwanted elements such as undefined values, dates, etc. from the structure.`,
      },
    ],
  };
};
